WebsiteBanTraiCay/WebsiteBanTraiCay/Models/ListOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebsiteBanTraiCay.Models
{
    public class ListOrder
    {
        public int ID { get; set; }
        public String CustomerName { get; set; }
        public double SAmount { get; set; }
        public int? Status { get; set; }
        public bool? IsPayment { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? ExportDate { get; set; }
        public string Username { get; set; }
        public int UserId { get; set; }
    }
}

WebsiteBanTraiCay/WebsiteBanTraiCay/Controllers/TrackOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanTraiCay.Models;

namespace WebsiteBanTraiCay.Controllers
{
    public class TrackOrderController : Controller
    {
        private ConnectDbContext db = new ConnectDbContext();
        // GET: TrackOrder
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection fc)
        {
            string phoneNumber = fc["phone"].ToString();
            var listOrder = db.Orders.Where(m => m.DeliveryPhone.Equals(phoneNumber)).OrderByDescending(m => m.ID).ToList();
            return View("listOrders", listOrder);
        }
        public ActionResult DetailOrder(int id)
        {
            var checkO = db.Orders.Where(m => m.Status !=0).ToList();
            if (checkO.Count() == 0)
            {
                
            }

            var id_order = db.Orders.Where(m => m.Status != 0).FirstOrDefault();
            ViewBag.Order = id_order;
            var itemOrder = db.Orderdetails.Where(m => m.OrderID == id_order.ID).ToList();
            ViewBag.productOrder = db.Products.ToList();
            return View(itemOrder);
            
        }
        public ActionResult productDetailCheckOut(int orderId)
        {
            var list = db.Orderdetails.Where(m => m.OrderID == orderId).ToList();
            return View("_productDetailCheckOut", list);

        }
        public ActionResult subnameProduct(int id)
        {
            var list = db.Products.Find(id);
            return View("_subproductOrdersuccess", list);

        }
    }
}

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/TrackOrder/Index.cshtml
@{
    ViewBag.Title = "Theo dõi đơn hàng";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<div class="breadcrumb-c clearfix d-block">
    <ul class="container-91">
        <li><a href="/">Trang chủ </a></li>
        <li class="dsfsd"><a href="#"> Theo dõi đơn hàng</a></li>
    </ul>
</div>

<div class="container-91 row my-2 mb-5">

    <div class="col-12">
        <div class="ml-2">
            <h2 class="my-4" style="text-align:center">THEO DÕI ĐƠN HÀNG</h2>
            <h5 class="information-text" style="text-align:center;">Nhập vào SĐT đặt hàng</h5>
            <div class="my-3">

            </div>

            <style>
                .form-contact input {
                    padding: 20px;
                    color: #333;
                }

                    .form-contact input::placeholder {
                        padding: 0;
                    }

                .form-contact textarea::placeholder {
                    padding: 0;
                }
            </style>

            <!--form-->
            <form action="" method="post">

                <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <input type="phone" name="phone" class="form-control rounded-0 py-4 bg-light" aria-describedby="emailHelp" placeholder="Nhập vào SDT đặt hàng" required="" style="">

                    </div>
                    <div class="col-md-4"></div>
                </div>

                <br style="margin-top:10px" />
                <div class="row">
                    <div class="col-md-5"></div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-dark ">
                            <small style="text-align:center">
                                XEM NGAY ĐƠN HÀNG
                            </small>
                        </button>
                    </div>
                    <div class="col-md-5"></div>
                </div>
                </form>
</div>
    </div>
</div>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/TrackOrder/_productDetailCheckOut.cshtml
@model IEnumerable<WebsiteBanTraiCay.Models.MOrderDetail>


<table class="table order-details-table">
    <thead>
        <tr>
            <th>Sản phẩm</th>
            <th>Tổng tiền</th>
        </tr>
    </thead>
    <tbody>
        @{ int sum = 0;}
        @foreach (var item in Model)
        {
            sum += (int)item.Amount;
            <tr>
                <td>
                    @Html.Action("subnameProduct", "TrackOrder", new { id = item.ProductID })
                    <strong>× @item.Quantity</strong>
                </td>
                <td><span>@item.Amount.ToString("N0") VND</span></td>
            </tr>
        }

    </tbody>
    <tfoot>
        <tr>
            <th>Tạm tính:</th>
            <td><span>@sum.ToString("N0") VND</span></td>
        </tr>
        <tr>
            <th>Phương thức thanh toán:</th>
            <td>Thanh toán khi nhận hàng</td>
        </tr>
        <tr>
            <th>Tổng:</th>
            <td><span>@sum.ToString("N0") VND</span></td>
        </tr>
    </tfoot>
</table>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/TrackOrder/_subproductOrdersuccess.cshtml
@model WebsiteBanTraiCay.Models.MProduct

<a href="~/@Model">@Model.Name</a>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/TrackOrder/listOrders.cshtml
@model IEnumerable<WebsiteBanTraiCay.Models.MOrder>
@{
    ViewBag.Title = "Theo dõi đơn hàng";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<div style="background:white; min-height:32rem; margin: 40px 0 100px 0">
    <div class="container-91 mx-auto">
        <!--<div class="col-3 mt-5">
        <div class="">
            <div class="float-left">-->
        @*<img src="images/boxed-bg.png" ralt="" width="50"
            class="rounded-circle">*@
        <!--</div>
                <div class="float-left pl-3 border-bottom">
                    <small class="font-weight-bold"> @Session["User_Name"]</small><br>

                </div>
            </div>
            <br>
            <div style="clear:both"></div>
            <div class="mt-4 pl-3">
                <ul class="nav flex-column">

                    <li class="nav-item">
                        <a class="nav-link text-secondary" href="order" style="font-size: 14px;">
                            <i class="far fa-file-alt"></i>
                            &nbsp Đơn mua
                        </a>
                    </li>


                </ul>
            </div>

        </div>-->
        <div class="col-12 bg- mt-3" style="">



            <div class="table-responsive-vertical tab-content shadow-z-1">
                <!-- Table starts here -->
                <table role="tabpanel" id="table" @*id="home"*@ class="@*tab-pane active*@ table table-hover table-mc-light-blue">
                    
                    <thead>

                        <tr>
                            <th style="border-top: none">Code</th>
                            <th style="border-top: none">Tên khách hàng</th>
                            <th style="border-top: none">Thời gian order</th>
                            <th style="border-top: none">Thời gian giao hàng(dự kiến)</th>
                            <th style="border-top: none">Trạng thái đơn hàng</th>
                            <th style="border-top: none">Chi tiết</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {


                            <tr>
                                <td class="image" data-title="No">@item.Code</td>
                                <td class="product-des" data-title="Description">
                                    <p class="product-name"><a href="#">@item.DeliveryName</a></p>

                                </td>
                                <td class="price" data-title="Price">   @item.CreateDate</td>

                                <td class="total-amount" data-title="Total">

                                    <strong class="text-danger">@item.ExportDate</strong>
                                </td>
                                <td>
                                    @if (item.Status == 2)
                                    {
                                        <span class="text-danger">Chờ duyệt</span>
                                    }
                                    else if (item.Status == 1)
                                    {
                                        <span class="text-danger">Đã hoàn thành</span>
                                    }
                                    else if (item.Status == 3)
                                    {
                                        <span class="text-danger">Đã Hủy</span>
                                    }
                                </td>

                                <td class="pro-subtotal"> <a href="trackings/@item.ID" target="_blank">Xem thêm</a></td>
                            </tr>

                        }
                    </tbody>

                </table>
            </div>


        </div>
    </div>
</div>


<style>
    #listtab-order .active {
        border-bottom: 3px solid #ee4d2d;
        background: #fff;
        color: #ee4d2d;
        border-top: 0;
        border-left: 0;
        border-right: 0;
    }

    .list-group-item {
        border-bottom: 1px solid #eee;
        border-top: 0;
        border-left: 0;
        border-right: 0;
    }

    .vertical-center {
        margin: 0 auto;
        position: absolute;
        top: 50%;
        -ms-transform: translateY(-50%);
        transform: translateY(-50%);
    }
</style>