WebsiteBanTraiCay/WebsiteBanTraiCay/Areas/Admin/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanTraiCay.Models;

namespace WebsiteBanTraiCay.Areas.Admin.Controllers
{
    public class ModulesController : Controller
    {
        private ConnectDbContext db = new ConnectDbContext();
        // GET: Admin/Modules
        public ActionResult LeftLayout()
        {
            return View();
        }
        public ActionResult LeftLayoutNoSession()
        {
            return View();
        }
        public ActionResult HeaderLayout()
        {
            ViewBag.Admins = db.Users.Where(m => m.Status != 0).First();
            return View();
        }
        public ActionResult LeftLayouts()
        {
            return View();
        }
    }
}

WebsiteBanTraiCay/WebsiteBanTraiCay/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanTraiCay.Models;

namespace WebsiteBanTraiCay.Controllers
{
    public class ModuleController : Controller
    {
        private ConnectDbContext db = new ConnectDbContext();
        // GET: Module
        public ActionResult Categories()
        {
            return View("_Categories", db.Categorys.Where(m=> m.Status == 1).ToList());
        }
        public ActionResult SlideShow()
        {
            // Position = 1 = SlideShow
            return View("_SlideShow", db.Sliders.Where(m => m.Status == 1 && m.Position == "1").ToList());
        }
        public ActionResult ConfigHead()
        {
            ViewBag.Configs = db.Configs.First();  
            return View();
        }
        public ActionResult ConfigAnalytic()
        {
            ViewBag.Configs = db.Configs.First();
            return View();
        }
        
        public ActionResult Header()
        {
            ViewBag.Promotion = db.Posts.Where(m => m.Status == 1 && m.Type == "post" && m.TopicID == 22).OrderByDescending(m => m.Created_at).Take(3).ToList();
            ViewBag.Configs = db.Configs.First();
            ViewBag.APITalkTo = db.Configs.First();
            var list = db.Categorys.Where(m => m.Status == 1).ToList();
            return View("_Header", list);
        }
        public ActionResult Footer()
        {
            //ViewBag.Title = db.Menus.Where(m => m.Status == 1 && m.Positon == "footer" && m.ParentID == 0).Take(2).ToList();
            ViewBag.Config = db.Configs.Take(1).ToList();
            ViewBag.Configs =  db.Configs.First();
            ViewBag.Page = db.Posts.Where(m => m.Status == 1 && m.Type == "page"&&m.Location== "customer").ToList();
            return View("_Footer", db.Menus.Where(m => m.Status == 1 && m.Positon == "footer").ToList());
        }
        public ActionResult HomeSlideShow()
        {
            ViewBag.Slider = db.Sliders.Where(m => m.Status == 1 && m.Position == "2").OrderByDescending(m => m.Created_at).Take(2).ToList();
            return View("_HomeSlideShow", db.Posts.Where(m => m.Status == 1 && m.Type == "post" && m.Position == "slider").ToList());
        }
        public ActionResult Popu()
        {
            return View("_Popu");
        }
        public ActionResult ListCategory()
        {
            var list = db.Categorys.Where(m => m.Status == 1 && m.ParentID == 0).ToList();
            return View("_ListCategory", list);
        }
        public ActionResult NewsHome()
        {
            return View("_NewsHome", db.Posts.Where(m => m.Status == 1 && m.Type == "post" && m.Position == "default").OrderByDescending(m => m.Created_at).Take(5).ToList());
        }
        public ActionResult Login()
        {
            return View("_Login");
        }
        public ActionResult MainMenu()
        {
            return View("_MainMenu", db.Menus.Where(m => m.Status == 1 && m.Positon == "header").ToList());
        }
        // partial page load with ajax
        public ActionResult MiTC()
        {
            return View("_MiTC");
        }
        public ActionResult ICart()
        {
            return View("_ICart");
        }
        public ActionResult ListPage()
        {
           
            return View("_ListPage", db.Posts.Where(m => m.Status == 1 && m.Type == "page" &&m.Location== "connect_footer").ToList());
        }
        public ActionResult EventHeader()
        {
            ViewBag.Eventnews = db.Event.Where(m => m.Status == 1).Take(2).OrderByDescending(m => m.Created_At).ToList();
            var list = db.Event.Where(m => m.Status == 1).Take(1).OrderBy(m => m.Created_At);
            return View("EventHeader", list);
        }
    }
}

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/Module/ConfigAnalytic.cshtml
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=@ViewBag.Configs.Analytic"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', '@ViewBag.Configs.Analytic');
</script>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/Module/ConfigHead.cshtml
<meta name="google-site-verification" content="@ViewBag.Configs.Analytic" />
<link rel="canonical" href="https://localhost:44370/" />
<meta name="description" content="Dịch vụ đăng ký mã GACC lệnh 248. Hiện nay có nhiều doanh nghiệp đã tự đăng ký mà chưa biết thủ tục và những quy định của thủ tục này ra sao?" />
<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
<meta property="og:locale" content="vi_VN" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Đăng ký mã GACC lệnh 248 chuyên nghiệp nhanh chóng" />
<meta property="og:description" content="Dịch vụ đăng ký mã GACC lệnh 248. Hiện nay có nhiều doanh nghiệp đã tự đăng ký mà chưa biết thủ tục và những quy định của thủ tục này ra sao?" />
<meta property="og:url" content="https://localhost:44370/" />
<meta property="og:site_name" content="Đăng ký mã GACC lệnh 248" />
<meta property="article:modified_time" content="2022-12-19T09:20:47+00:00" />
<meta property="og:image" content="https://dangkymagacclenh248.com/wp-content/uploads/2022/10/xuat-khau-nong-san-sang-trung-qu-1024x582.jpg" />
<link rel="icon" href="~/Public/images/iconweb/@ViewBag.Configs.LogoIconWeb">

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/Module/EventHeader.cshtml
@model IEnumerable<WebsiteBanTraiCay.Models.MEvent>

<div class="header__top-bar__left">
    @if (Model.Count() != 0)
    {
        foreach (var events in ViewBag.Eventnews)
        {
            <a href="~/@events.URL" class="top-bar__left__title" style="margin-bottom: 0">
               @events.Name
            </a>

        }
    }
    else
    {
        <a href="#" class="top-bar__left__title" style="margin-bottom: 0">
            Hiện chưa có chương trình KM
        </a>
    }

</div>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/Module/_Categories.cshtml
@model IEnumerable<WebsiteBanTraiCay.Models.MCategory>
    
<style>
    .menu-content-items {
        position: relative
    }

        .menu-content-items:hover .menu-content-list-nav {
            opacity: 1;
            visibility: visible
        }

    .menu-content-list-nav {
        box-shadow: 0px 0px 5px 0px rgb(0 0 0 / 17%);
        position: absolute;
        width: 300px;
        min-height: 100px;
        top: 0;
        left: 259px;
        z-index: 99999;
        background: white;
        list-style: none;
        opacity: 0;
        visibility: hidden;
        transition: 0.2s all ease
    }

        .menu-content-list-nav li {
            padding: 0 20px
        }

            .menu-content-list-nav li a {
                color: #555
            }
</style>
<div class="shop-sidebar">
    <aside class="nav-menu">
        <p class="nav-menu-title" style="margin: 0">
            DANH MỤC SẢN PHẨM
        </p>
        <div class="nav-menu-content">
            <ul class="menu-content-list">
                <li class="menu-content-items"> <a href="~/product"> Tất cả sản phẩm</a></li>

                @{int i = 1; }
                @foreach (var c in Model@*.Take(12)*@)
{
if (c.ParentID == 0)
{
            <li class="menu-content-items">
                <a href="~/@c.Slug">@c.Name</a>
                @*<ul class="menu-content-list-nav">
                    @foreach (var d in Model)
                    {
                        if (c.ID == d.ParentID)
                        {
                            <li>
                                <a href="~/@d.Slug" class="">@d.Name</a>
                            </li>
                        }
                    }
                </ul>*@
            </li>

        }
    }

            </ul>

        </div>
    </aside>


</div>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/Module/_Footer.cshtml
@model IEnumerable<WebsiteBanTraiCay.Models.MMenu>
<footer class="" style=" background: #ffe6dd ">
    <div class="row container-91" style="padding: 30px 0">
        <div class="col-3">
            <div class="title text-uppercase font-weight-bold">Về chúng tôi</div>
            @foreach (var config in ViewBag.Config)
            {
                <a href="javascript:void(0)" class="ll text-decoration-none text-dark" style="display:flex; align-items:center "> <i class="fa-solid fa-location-dot"></i> <span class="" style="margin-left: 10px"><b>Địa chỉ:</b> @config.Address</span></a>
                <a href="javascript:void(0)" class="ll text-decoration-none text-dark" style="display: flex; align-items: center"> <i class="fa-solid fa-phone"></i> <span class="" style="margin-left: 10px"><b>SĐT:</b> @string.Format("0{0:#### ### ###}", Convert.ToInt64(config.Phone)) (8:30 - 17:00)</span></a>
                <a href="javascript:void(0)" class="ll text-decoration-none text-dark" style="display: flex; align-items: center"> <i class="fa-solid fa-envelope"></i> <span class="" style="margin-left: 10px"><b>Email:</b> @config.Gmail</span></a>
            }

        </div>

        <div class="col-3">
            <div class="title  font-weight-bold">LIÊN LẠC VỚI CHÚNG TÔI</div>
            @foreach (var config in ViewBag.Config)
            {
                <a href="javascript:void(0)" class="ll text-decoration-none text-dark"> Đặt hàng: <b>@string.Format("0{0:#### ### ###}", Convert.ToInt64(config.Phone)) </b></a>
                <a href="javascript:void(0)" class="ll text-decoration-none text-dark"> Hotline 24/7: <b>@string.Format("0{0:#### ### ###}", Convert.ToInt64(config.Phone_1))</b></a>

            }



        </div>
        <div class="col-3">
            <div class="title font-weight-bold">KHÁCH HÀNG</div>
            @foreach (var page in ViewBag.Page)
            {
                <a href="@page.Slug" class="ll text-decoration-none text-dark" style="display:flex; align-items:center ">  <span class="">@page.Title</span></a>
            }



        </div>
        <div class="col-md-3">
            <div class="title text-uppercase font-weight-bold">KẾT NỐI VỚI CHÚNG TÔI</div>
            @Html.Action("ListPage","Module")            

        </div>
    </div>

</footer>
<link href="~/Public/css/stylecontact.css" rel="stylesheet" />
<div class="box_fixRight2">
    <div class="box_content2">

    </div>
</div>
<script type="text/javascript">
    var abc = $('.box_content2');
    $(window).scroll(function () {
        abc.css("opacity", 1 - $(window).scrollTop() / $(document).height() * 2);

        if ($(window).scrollTop() + $(window).height() > $(document).height() - 500) {
            abc.fadeTo(1000, 1);
        }
        else if ($(window).scrollTop + $(window).height() == $(document).height() - 500) {
            abc.css("opacity", 1 - $(window).scrollTop() / $(document).height());
        }
    });
</script>


<div class="box_fixRight">
    <div class="box_content">
        <a href="https://zalo.me/@ViewBag.Configs.Zalo" target="_blank" class="item item_1">Chat Zalo</a>
        <a href="https://m.me/legialai98.hitu" target="_blank" class="item item_3">Messenger</a>
        <a href="tel:@ViewBag.Configs.Phone" class="item item_2" target="_blank">Gọi ngay</a>
    </div>
</div>
<div class="footer__item">
    <div class="footer__contact">
        <a href="https://zalo.me/@ViewBag.Configs.Zalo" target="_blank">
            <img src="~/Public/images/social/logo-zalo.png" alt="">
            <p>Liên hệ zalo</p>
        </a>
    </div>
    <div class="footer__call">
        <a href="tel:@ViewBag.Configs.Phone" target="_blank">
            <i class="fa fa-phone"></i>
            <p>Gọi ngay</p>
        </a>
    </div>
</div>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/Module/_Header.cshtml
@model IEnumerable<WebsiteBanTraiCay.Models.MCategory>
<head>
    <link rel="stylesheet" href="~/Public/css/styleHeader.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   
</head>
<header>
    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/@ViewBag.APITalkTo.APITalkTo';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->

    @*<div class="" style="background:rgb(29, 113, 171)">
            <div class="container-91 text-right">
                <small>
                    @Html.Action("MainMenu", "Module")
                </small>
            </div>
        </div>*@

    <div id="header">
        <div class="header__wrapper">
            <div id="header__top-bar" class="header__top-bar ">
                <div class="container">
                    @Html.Action("EventHeader", "Module")
                    <div class="header__top-bar__right">
                        <ul class="header__right__list" style="margin-bottom: 0">
                            <li class="header__right__language">
                                <a href="tracking">
                                    Theo dõi đơn hàng
                                </a>
                            </li>
                            <li class="header__right__language">
                                <a href="forgotpassword">
                                    Tìm lại mật khẩu
                                </a>
                                @*<i class="fa-solid fa-chevron-down"></i>
            <div class="right__language__current-dropdown">
                <p>You need Polylang or WPML plugin for this to work. You can remove it from Theme Options.</p>
            </div>*@
                            </li>
                            <li class="header__right__divider"></li>
                            <li class="header__right__social">
                                <i class="fa-brands fa-facebook-f"></i>
                                <i class="fa-brands fa-instagram"></i>
                                <i class="fa-brands fa-twitter"></i>
                            </li>

                            @*<li class="header__right__divider"></li>
                            <li class="header__right__language">
                                <a href="#">
                                    Language

                                </a>
                                <i class="fa-solid fa-chevron-down"></i>
                                <div class="right__language__current-dropdown">
                                    <p>You need Polylang or WPML plugin for this to work. You can remove it from Theme Options.</p>
                                </div>
                            </li>*@
                        </ul>
                    </div>
                </div>

            </div>
            <div class="header__main">
                <div class="container">
                    <div class="header__main__logo">
                        <a href="/">
                            <img src="~/Public/images/iconweb/@ViewBag.configs.LogoWeb" alt="@ViewBag.configs.Name" width="90" height="27">
                        </a>
                    </div>
                    <div class="header__main__nav">
                        <ul class="header__main__nav__list">
                            <li class="header__main__nav__item"> <a class="header__main__nav_link" href="/">TRANG CHỦ</a></li>
                            <li class="header__main__nav__item"><a class="header__main__nav_link" href="about">GIỚI THIỆU</a> </li>
                            <li class="header__main__nav__item">
                                <a class="header__main__nav_link" href="~/product">
                                    CỬA HÀNG
                                    <i class="fa-solid fa-chevron-down"></i>
                                </a>
                                <div class="main__nav__item__current-dropdown">
                                    <ul class="current-dropdown__list">
                                        <li class="current-dropdown__item">

                                            <a class="current-dropdown__link" href="~/product">Tất cả sản phẩm</a>
                                        </li>

                                        @{int i = 1; }
                                        @foreach (var c in Model@*.Take(12)*@)
    {
        if (c.ParentID == 0)
        {
                        <li class="current-dropdown__item">

                            <a class="current-dropdown__link" href="~/@c.Slug">@c.Name</a>
                            @*<ul class="current-dropdown__list-nav">

            @foreach (var d in Model)
            {
                if (c.ID == d.ParentID)
                {

                    <li class="">
                        <a href="~/@d.Slug" class="current-dropdown__link">@d.Name</a>
                    </li>
                }
            }
        </ul>*@
                        </li>
                    }
                    i++;
                }
                                    </ul>
                                    <div class="">
                                        @foreach (var t in ViewBag.Promotion)
                                        {
                                            <div class="promo float-left"> <a href="@t.Slug" class="text-dark text-decoration-none">@t.Title</a> </div>
                                        }

                                    </div>
                                </div>
                            </li>

                            @Html.Action("MainMenu", "Module")
                            <li class="header__main__nav__item"><a class="header__main__nav_link" href="@Url.Action("Contact","Site")">LIÊN HỆ</a> </li>
                        </ul>
                    </div>
                    <div class="header__main__nav-right">
                        <ul class="header__main__nav-right__list">
                            <li class="main__nav-right__item">
                                <a class="main__nav-right__item__link" href="">
                                    <i class="fa-solid fa-magnifying-glass"></i>
                                </a>
                                <div class="main__nav__item-search">
                                    @using (Html.BeginForm("Search", "Site", FormMethod.Get, new { @class = "form-search-top" }))
                                    {
                                        <div class="main__nav__item-box-search">

                                            <input type="text" name="key" id="" value="@(Session["keywords"] ?? "")" placeholder="Tìm kiếm...">
                                            <button type="submit">
                                                <i class="fa-solid fa-magnifying-glass"></i>
                                            </button>


                                        </div>
                                    }
                                </div>
                            </li>

                            <li class="main__nav-right__item  main__nav-right__item__link-user">
                                <p class="main__nav-right__item__link">
                                    @Html.Action("Login", "Module")

                                </p>

                            </li>
                            <li class="main__nav-right__item">
                                <a class="main__nav-right__item__link " href="~/cart">

                                    <i class="fa-solid fa-cart-shopping"></i>
                                    <div class="main__nav-right__item-cart">
                                        <div class="main__nav-right__item-cart-count">
                                            <span class="count-cart slc">
                                                @(Session["Cart"] != null ? ((List<WebsiteBanTraiCay.Library.ModelCart>)Session["Cart"]).Count() : 0)
                                            </span>

                                        </div>
                                    </div>
                                </a>
                                <div class=" list-cart">

                                    @if (Session["Cart"] != null)
                                    {
                                        <div class="cart-box">
                                            @{double Tong = 0;}
                                            @foreach (var c in (List<WebsiteBanTraiCay.Library.ModelCart>)Session["Cart"])
                                            {
                                                Tong += (c.Price * c.Quantity);


                                                <div class="cart-box-item">
                                                    <a class="cart-box-item-img-link" href="~/@c.Slug">
                                                        <img class="cart-box-item-img" src="~/Public/images/products/@c.Image" alt="@c.Name">
                                                    </a>
                                                    <div class="cart-box-item-info">
                                                        <div class="cart-box-item-name">
                                                            <a class="cart-box-item-name-link" href="~/@c.Slug">@c.Name</a>
                                                        </div>
                                                        <div class="cart-box-item-quantity-price">
                                                            <span class="cart-box-item-price">@c.Price.ToString("N0") ₫</span>
                                                            <span> x</span>
                                                            <div class="quantity-product">
                                                                <span class="cart-box-item-quantity">@c.Quantity</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="remove-cart">
                                                        <a href="javascript:void(0)" data-toggle="tooltip" data-placement="right" class="m-remove-one"
                                                           data-id="@c.ProductID" title="Xóa khỏi giỏ hàng">
                                                            <i class="fa-solid fa-x"></i>
                                                        </a>
                                                    </div>
                                                </div>

                                            }
                                        </div>

                                        <div class="total-price-box">
                                            <span>Tạm tính:</span>
                                            @Tong.ToString("N0")₫
                                            <div class="total-price"> </div>
                                        </div>

                                        <div class="btn-cart-box-buy">
                                            <a class="btn-cart-link-buy" href="~/cart">THANH TOÁN</a>

                                        </div>
                                    }
                                    else
                                    {
                                        <div class="t text-center">
                                            <img src="~/Public/images/null.png" alt="Trống" width="100">
                                            <div class="pb-5 font-weight-bold " style="opacity: .6;">
                                                Giỏ hàng của bạn trống
                                            </div>
                                        </div>
                                    }

                                </div>




                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

</header>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/Module/_HomePost.cshtml
@model IEnumerable<WebsiteBanTraiCay.Models.MPost>
<div class="col-sm-2">
    <div class="exp-news">
        <div class="pl-2 py-2 border-bottom border-light">
            <div class="fb-like" data-href="https://www.facebook.com/Gia-D%E1%BB%A5ng-R%E1%BA%BB-Gia-Lai-108487101091890" data-width="" data-layout="button_count" data-action="like" data-size="small" data-share="true"></div>
        </div>
        <div class="title text-dark font-weight-bold">
            <a href="~/tin-tuc" class="text-dark text-decoration-none">TIN TỨC NỔI BẬT - MỚI NHẤT</a> <i class="fas fa-caret-right"></i>
        </div>

        @foreach (var u in Model)
        {
            <div class="des-exp">

                <a href="~/@u.Slug" class="text-dark text-decoration-none">

                    @u.Title
                </a>
            </div>
        }
        <div class="mb-4"></div>
        
    </div>
</div>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/Module/_HomeSlideShow.cshtml
@model IEnumerable<WebsiteBanTraiCay.Models.MPost> 
<head>
    <link href="~/Public/css/styleContent.css" rel="stylesheet" />
</head>
<div class="row clearfix">
    @*<div class="col-sm-3 p-0 m-0">
            @Html.Action("Categories", "Module")
        </div>*@
    <div class="col-sm-12">
        @Html.Action("SlideShow", "Module")
    </div>
        @*<div class="col-sm-2">
            <div class="exp-news">
                <div class="pl-2 py-2 border-bottom border-light">
                    <div class="fb-like" data-href="https://www.facebook.com/Gia-D%E1%BB%A5ng-R%E1%BA%BB-Gia-Lai-108487101091890" data-width="" data-layout="button_count" data-action="like" data-size="small" data-share="true"></div>
                </div>
                <div class="title text-dark font-weight-bold">
                    <a href="~/tin-tuc" class="text-dark text-decoration-none">TIN TỨC NỔI BẬT - MỚI NHẤT</a> <i class="fas fa-caret-right"></i>
                </div>

                @foreach (var u in Model)
                {
            <div class="des-exp">

                <a href="~/@u.Slug" class="text-dark text-decoration-none">

                    @u.Title
                </a>
            </div>
                }
            <div class="mb-4"></div>
                @foreach (var t in ViewBag.Slider)
                {
                    <div class="my-1 pl-2">
                        <a href="@t.Url" class="my-5"><img src="~/Public/images/sliders/@t.Image" alt="@t.Name"></a>
                    </div>
                }
            </div>
        </div>*@
</div>
<!--Selection-content-->
<div class=" selection-content">
    <div class="selection-content__banner container">
        <div class="selection-content__banner-item">
            <img src="~/Public/images/banners/web-campain-06-1024x1024.jpg" alt="">
            <div class="selection__text-content">

                <a class="button" href="~/product">
                    <span class="button__buy">Mua Ngay</span>
                    <span class="button__divider"></span>
                </a>
            </div>
        </div>
        <div class="selection-content__banner-item">
            <img src="~/Public/images/banners/web-campain-07-1024x1024.jpg"  width="90%" alt="">
            <div class="selection__text-content">
 
                <a class="button" href="~/product">
                    <span class="button__buy">Mua Ngay</span>
                    <span class="button__divider"></span>
                </a>
            </div>

        </div>
        <div class="selection-content__banner-item">
            <img src="~/Public/images/banners/web-campain-09-1024x1024.jpg" alt="">
            <div class="selection__text-content">
      
                <a class="button" href="~/product">
                    <span class="button__buy">Mua Ngay</span>
                    <span class="button__divider"></span>
                </a>
            </div>
        </div>
    </div>

</div>
<!--Policy-->
<div class="policy">
    <div class="policy__box container">
        <div class="policy__box-item">
            <div class="policy__box-img">
                <img src="~/Public/images/free_shipping.png" alt="">
            </div>
            <div class="policy__box-box">
                <div class="policy__box-content">
                    <p>MIỄN PHÍ VẬN CHUYỂN</p>
                    <p>Miễn Phí Tất Cả Đơn Hàng</p>
                </div>
            </div>

        </div>
        <div class="policy__box-item">
            <div class="policy__box-img">
                <img src="~/Public/images/support247.png" alt="">
            </div>
            <div class="policy__box-box">
                <div class="policy__box-content">
                    <p>HỖ TRỢ 24/7</p>
                    <p> Hỗ trợ 24 Giờ Một Ngày</p>
                </div>
            </div>
        </div>
        <div class="policy__box-item">
            <div class="policy__box-img">
                <img src="~/Public/images/money_back.png" alt="">
            </div>
            <div class="policy__box-box">
                <div class="policy__box-content">
                    <p>HOÀN TIỀN</p>
                    <p>Hoàn Tiền Trong 30 Ngày</p>
                </div>
            </div>
        </div>
        <div class="policy__box-item">
            <div class="policy__box-img">
                <img src="~/Public/images/promotions.png" alt="">
            </div>
            <div class="policy__box-box">
                <div class="policy__box-content">
                    <p>GIẢM GIÁ</p>
                    <p>Với Đơn Hàng Trên 1 Triệu</p>
                </div>
            </div>
        </div>
    </div>
</div>

WebsiteBanTraiCay/WebsiteBanTraiCay/Views/Module/_ListPage.cshtml
@model IEnumerable<WebsiteBanTraiCay.Models.MPost>

@foreach (var k in Model)
{

    <a href="~/@k.Slug" class="ll text-decoration-none text-dark" style="display:flex; align-items:center ">  <span class="">@k.Title</span></a>

}    